# Generated by Django 2.2 on 2022-07-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.CourseCategory'),
        ),
    ]
